version: '3'

services:
  frontend:
    build: 
      context: .
      dockerfile: ./docker/front/DockerFile
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd frontend && yarn start'
    restart: always
    ports:
      - '3000:3000'
    tty: true
