services:
  front:
    build:
      context: .
      dockerfile: ./docker/front/DockerFile # frontディレクトリでコンテナをビルドする
    container_name: front
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./front/src/:/app/
    tty: true # コンテナを起動し続ける
    working_dir: /app/todo-vite-app
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/DockerFile
    container_name: backend
    restart: always
    # ports はホストからアクセス可、expose はホストからアクセス不可なポート。
    ports:
      - "8080:8080" # 8080番ポートを内部ネットワークに公開
    volumes:
      - ./backend/sample-api/:/app/
    tty: true
  db:
    container_name: mysql
    tty: true
    image: mysql:8.0
    volumes:
      - ./database/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
      MYSQL_USER: user
      MYSQL_PASSWORD: P@ssw0rd
      TZ: 'Asia/Tokyo'
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

